### PR TITLE
Fix Prevent XSS vulnerability in default theme

### LINKED ISSUE #1650: Typecho v1.2.1 存储型 XSS 漏洞
# 描述
Typecho 管理后端设置外观中， 设置站点的 LOGO 地址处存在存储型 XSS 漏洞
1. 登录管理员后台
2. 前往 `/admin/options-theme.php` 修改网站的 LOGO 地址
3. 在 LOGO 地址处添加 XSS 的payload   `" onerror="alert('XSS')`
image-20231128145446172
4. 之后访问主页面可以发现 XSS 的 payload 被触发
image-20231128145413146
Snipaste_2023-11-29_15-53-04

### PR DESCRIPTION
**Pull request by sy-records**
fix #1650

### CODE REVIEW

File: var/Typecho/Db/Adapter/Pdo.php [hunk 1]
```diff
@@ -29,9 +29,9 @@ abstract class Pdo implements Adapter
      * 最后一次操作的数据表
      *
      * @access protected
-     * @var string
+     * @var ?string
```
Comment (sy-records) [inline var/Typecho/Db/Adapter/Pdo.php:32]:
```suggestion
     * @var string|null
```
